In [3]:
import requests
import pandas as pd 
import numpy as np

In [16]:
response = requests.get("https://api.bigbookapi.com/search-books?query=books+about+wizards&api-key=444e1a6f644c415792d65b6eec65c0b8")

In [52]:
data = response.json()
books = data["books"]
print(f"Type of the Books data is : {type(books)}")
print(f"Lenght of the books_data is : {len(books)}")
books[0]

Type of the Books data is : <class 'list'>
Lenght of the books_data is : 10

[{'id': 17200576,
  'title': 'Journey to Hogwarts',
  'image': 'https://covers.openlibrary.org/b/id/2520429-M.jpg',
  'authors': [{'id': 14136020, 'name': 'J. K. Rowling'}],
  'rating': {'average': 0.8939999938011169}}]

In [61]:

books_list = []
for book in books:
    books_list.append(book[0])

books_list

[{'id': 17200576,
  'title': 'Journey to Hogwarts',
  'image': 'https://covers.openlibrary.org/b/id/2520429-M.jpg',
  'authors': [{'id': 14136020, 'name': 'J. K. Rowling'}],
  'rating': {'average': 0.8939999938011169}},
 {'id': 15954006,
  'title': 'Inside Hogwarts',
  'subtitle': 'Magical Paintbook',
  'image': 'https://covers.openlibrary.org/b/id/2520430-M.jpg',
  'authors': [{'id': 14136020, 'name': 'J. K. Rowling'}],
  'rating': {'average': 0.8939999938011169}},
 {'id': 16384516,
  'title': 'Harry Potter and the Goblet of Fire',
  'image': 'https://covers.openlibrary.org/b/id/12775900-M.jpg',
  'authors': [{'id': 14136020, 'name': 'J. K. Rowling'}],
  'rating': {'average': 0.9120000004768372}},
 {'id': 14296534,
  'title': 'Harry Potter and the Order of the Phoenix',
  'image': 'https://covers.openlibrary.org/b/id/11416565-M.jpg',
  'authors': [{'id': 14136020, 'name': 'J. K. Rowling'}],
  'rating': {'average': 0.8999999761581421}},
 {'id': 14530450,
  'title': 'Great Gatsby (Silver Screen Edition)',
  'image': 'https://covers.openlibrary.org/b/id/12791857-M.jpg',
  'authors': [{'id': 13033216, 'name': 'Zondervan Publishing Company'}],
  'rating': {'average': 0.7860000133514404}},
 {'id': 18810398,
  'title': 'The Hobbit',
  'subtitle': 'or, There and back again',
  'image': 'https://covers.openlibrary.org/b/id/394001-M.jpg',
  'authors': [{'id': 13038776, 'name': 'J.R.R. Tolkien'}],
  'rating': {'average': 0.8560000061988831}},
 {'id': 27067084,
  'title': 'The Fellowship of the Ring',
  'image': 'https://covers.openlibrary.org/b/id/13530646-M.jpg',
  'authors': [{'id': 13038776, 'name': 'J.R.R. Tolkien'},
   {'id': 27067082, 'name': 'Rob Inglis'}],
  'rating': {'average': 0.8799999952316284}},
 {'id': 13597674,
  'title': 'The Name of the Wind',
  'subtitle': 'The Kingkiller Chronicle : day one',
  'image': 'https://covers.openlibrary.org/b/id/6282709-M.jpg',
  'authors': [{'id': 13597658, 'name': 'Patrick Rothfuss'}],
  'rating': {'average': 0.9039999842643738}},
 {'id': 20778556,
  'title': 'Two Towers : The Lord of the Rings',
  'subtitle': 'Part Two',
  'image': 'https://covers.openlibrary.org/b/id/13220226-M.jpg',
  'authors': [{'id': 13038776, 'name': 'J.R.R. Tolkien'}],
  'rating': {'average': 0.8939999938011169}},
 {'id': 20101114,
  'title': 'Frankenstein (Silver Screen Edition)',
  'image': 'https://covers.openlibrary.org/b/id/12791860-M.jpg',
  'authors': [{'id': 13033216, 'name': 'Zondervan Publishing Company'}],
  'rating': {'average': 0.7699999809265137}}]

In [64]:
print(f"type of book_list : {type(books_list)}")
print(f"type of book_list[0] : {type(books_list[0])}")
print(f"Book list keys : {books_list[0].keys()}")

type of book_list : <class 'list'>
type of book_list[0] : <class 'dict'>
Book list keys : dict_keys(['id', 'title', 'image', 'authors', 'rating'])

In [71]:
df = pd.DataFrame(books_list)
df

,id,title,image,authors,rating,subtitle
0,17200576,Journey to Hogwarts,https://covers.openlibrary.org/b/id/2520429-M.jpg,"[{'id': 14136020, 'name': 'J. K. Rowling'}]",{'average': 0.8939999938011169},NaN
1,15954006,Inside Hogwarts,https://covers.openlibrary.org/b/id/2520430-M.jpg,"[{'id': 14136020, 'name': 'J. K. Rowling'}]",{'average': 0.8939999938011169},Magical Paintbook
2,16384516,Harry Potter and the Goblet of Fire,https://covers.openlibrary.org/b/id/12775900-M...,"[{'id': 14136020, 'name': 'J. K. Rowling'}]",{'average': 0.9120000004768372},NaN
3,14296534,Harry Potter and the Order of the Phoenix,https://covers.openlibrary.org/b/id/11416565-M...,"[{'id': 14136020, 'name': 'J. K. Rowling'}]",{'average': 0.8999999761581421},NaN
4,14530450,Great Gatsby (Silver Screen Edition),https://covers.openlibrary.org/b/id/12791857-M...,"[{'id': 13033216, 'name': 'Zondervan Publishin...",{'average': 0.7860000133514404},NaN
5,18810398,The Hobbit,https://covers.openlibrary.org/b/id/394001-M.jpg,"[{'id': 13038776, 'name': 'J.R.R. Tolkien'}]",{'average': 0.8560000061988831},"or, There and back again"
6,27067084,The Fellowship of the Ring,https://covers.openlibrary.org/b/id/13530646-M...,"[{'id': 13038776, 'name': 'J.R.R. Tolkien'}, {...",{'average': 0.8799999952316284},NaN
7,13597674,The Name of the Wind,https://covers.openlibrary.org/b/id/6282709-M.jpg,"[{'id': 13597658, 'name': 'Patrick Rothfuss'}]",{'average': 0.9039999842643738},The Kingkiller Chronicle : day one
8,20778556,Two Towers : The Lord of the Rings,https://covers.openlibrary.org/b/id/13220226-M...,"[{'id': 13038776, 'name': 'J.R.R. Tolkien'}]",{'average': 0.8939999938011169},Part Two
9,20101114,Frankenstein (Silver Screen Edition),https://covers.openlibrary.org/b/id/12791860-M...,"[{'id': 13033216, 'name': 'Zondervan Publishin...",{'average': 0.7699999809265137},NaN

In [73]:
df['rating_average'] = df['rating'].apply(
    lambda x: x.get('average') if isinstance(x, dict) else None
)

df.drop(columns=['rating'], inplace=True)

In [74]:
df['authors'] = df['authors'].apply(
    lambda x: ', '.join(a['name'] for a in x) if isinstance(x, list) else None
)

In [75]:
df.head()

,id,title,image,authors,subtitle,rating_average
0,17200576,Journey to Hogwarts,https://covers.openlibrary.org/b/id/2520429-M.jpg,J. K. Rowling,NaN,0.894
1,15954006,Inside Hogwarts,https://covers.openlibrary.org/b/id/2520430-M.jpg,J. K. Rowling,Magical Paintbook,0.894
2,16384516,Harry Potter and the Goblet of Fire,https://covers.openlibrary.org/b/id/12775900-M...,J. K. Rowling,NaN,0.912
3,14296534,Harry Potter and the Order of the Phoenix,https://covers.openlibrary.org/b/id/11416565-M...,J. K. Rowling,NaN,0.900
4,14530450,Great Gatsby (Silver Screen Edition),https://covers.openlibrary.org/b/id/12791857-M...,Zondervan Publishing Company,NaN,0.786

In [82]:
df.isna().sum()

id                0
title             0
image             0
authors           0
subtitle          0
rating_average    0
dtype: int64

In [79]:
df.dropna(inplace=True)

In [81]:
df.isnull().sum()

id                0
title             0
image             0
authors           0
subtitle          0
rating_average    0
dtype: int64

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 1 to 8
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              4 non-null      int64
 1   title           4 non-null      object
 2   image           4 non-null      object
 3   authors         4 non-null      object
 4   subtitle        4 non-null      object
 5   rating_average  4 non-null      float64
dtypes: float64(1), int64(1), object(4)
memory usage: 224.0+ bytes

In [84]:
df.describe()

                 id  rating_average
count  4.000000e+00        4.000000
mean   1.728516e+07        0.887000
std    3.156986e+06        0.021197
min    1.359767e+07        0.856000
25%    1.536492e+07        0.884500
50%    1.738220e+07        0.894000
75%    1.930244e+07        0.896500
max    2.077856e+07        0.904000

In [86]:
df.to_csv("books_data.csv")