In [2]:
import requests
import pandas as pd

In [3]:
r = requests.get("https://arbeitnow.com/api/job-board-api")

In [4]:
json = r.json()
df = pd.DataFrame(json['data']) 
df.tail()

,slug,company_name,title,description,remote,url,tags,job_types,location,created_at
95,chartermitarbeiter-mit-verantwortung-perspekti...,Aquare Charter GmbH,Chartermitarbeiter (m/w/d) mit Verantwortung &...,<p>Die Aquare Charter GmbH steht für Urlaub di...,False,https://www.arbeitnow.com/jobs/companies/aquar...,[Customer Service],[berufserfahren],Brandenburg,1768397545
96,werkstudent-oder-masterand-sensorentwicklung-i...,Xylem Water Solutions,Werkstudent oder Masterand Sensorentwicklung (...,<p>Schließe Dich Xylem bei der globalen Missio...,False,https://www.arbeitnow.com/jobs/companies/xylem...,[Engineering],[Working student],Weilheim in Oberbayern,1768397544
97,mitarbeiter-fur-den-charter-stutzpunkt-standor...,Aquare Charter GmbH,Mitarbeiter (m/w/d) für den Charter-Stützpunkt...,<p>Die Aquare Charter GmbH steht für Urlaub di...,False,https://www.arbeitnow.com/jobs/companies/aquar...,[Customer Service],[],Lychen,1768413542
98,communications-consultant-bei-frauwenk-berlin-...,FRAUWENK,Communications Consultant (m/w/d) bei FRAUWENK,"<p>Du suchst keine klassische Agentur, sondern...",False,https://www.arbeitnow.com/jobs/companies/frauw...,"[Public Relations, Corporate Communication]",[berufserfahren],Berlin,1768397543
99,qa-engineer-firmware-mobile-testing-munich-318487,Bragi,QA Engineer - Firmware & Mobile Testing,<p>Bragi was founded in 2013 and launched the ...,True,https://www.arbeitnow.com/jobs/companies/bragi...,"[Remote, Engineering]",[professional / experienced],Munich,1768397542

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   slug          100 non-null    object
 1   company_name  100 non-null    object
 2   title         100 non-null    object
 3   description   100 non-null    object
 4   remote        100 non-null    bool
 5   url           100 non-null    object
 6   tags          100 non-null    object
 7   job_types     100 non-null    object
 8   location      100 non-null    object
 9   created_at    100 non-null    int64
dtypes: bool(1), int64(1), object(8)
memory usage: 7.3+ KB

In [16]:
df["created_at"] = pd.to_datetime(df["created_at"])

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   slug          100 non-null    object
 1   company_name  100 non-null    object
 2   title         100 non-null    object
 3   description   100 non-null    object
 4   remote        100 non-null    bool
 5   url           100 non-null    object
 6   tags          100 non-null    object
 7   job_types     100 non-null    object
 8   location      100 non-null    object
 9   created_at    100 non-null    datetime64[ns]
dtypes: bool(1), datetime64[ns](1), object(8)
memory usage: 7.3+ KB

In [18]:
df.head()

,slug,company_name,title,description,remote,url,tags,job_types,location,created_at
0,showroom-event-feelgood-manager-hamburg-204640,1KOMMA5˚,"Showroom, Event & Feelgood Manager (m/w/d) - H...",<h2>1KOMMA5°</h2>\n<p>Bei <strong>1KOMMA5°</st...,False,https://www.arbeitnow.com/jobs/companies/1komm...,[Customer Service],[berufseinstieg],Hamburg,1970-01-01 00:00:01.768415543
1,werkstudent-marketing-hamburg-45919,Triviar Education GmbH,Werkstudent Marketing (m/w/d),<p>🌟 <strong>WIR SUCHEN DICH</strong> 🌟</p>\n<...,False,https://www.arbeitnow.com/jobs/companies/trivi...,[Marketing Assistant],[Working student],Hamburg,1970-01-01 00:00:01.768413729
2,dlp-data-leakage-prevention-engineer-munich-12...,Mandl. Executives & Experts,DLP (Data Leakage Prevention) Engineer (m/w/d),"<p>Du möchtest aktiv dazu beitragen, dass vert...",True,https://www.arbeitnow.com/jobs/companies/mandl...,"[Remote, Information Systems]",[berufserfahren],Munich,1970-01-01 00:00:01.768413728
3,regional-development-manager-everyone-is-welco...,Sirius Facilities GmbH,Regional Development Manager (everyone is welc...,<h2>Deine Aufgaben</h2>\n<ul>\n<li>Gesamtveran...,False,https://www.arbeitnow.com/jobs/companies/siriu...,[Software Development],[berufserfahren],Frankfurt,1970-01-01 00:00:01.768411947
4,working-student-machine-learning-engineer-muni...,Delicious Data GmbH,Working Student Machine Learning Engineer (f/m/d),<p>Hey! We’re Delicious Data 👋</p>\n<p>We buil...,False,https://www.arbeitnow.com/jobs/companies/delic...,[Data Scientist],[Working student],Munich,1970-01-01 00:00:01.768410124

In [20]:
df.to_excel('jobs_updated.xlsx')